[package]
name = "rust-env-replacer"
version = "0.1.0"
authors = ["Eduard Kyvenko <eduard.kyvenko@gmail.com>"]
edition = "2018"

[dependencies]
glob = "0.3.0"
clap = { git = "https://github.com/clap-rs/clap/" }